### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by ageis** [HLFH/OpenPGP-Secure#1]
This is more like positive feedback than a ticket, so you may close it straight away, but I was pleased to learn of the `--openpgp` switch to `systemd-resolve`. Had no idea about that previously.

Here's a guide for using a single smartcard for GPG and SSH, in case you find it useful or want to add it to relevant links:

- https://gist.github.com/ageis/14adc308087859e199912b4c79c4aaa4

Here's [who I am](https://cointel.pro), also [@ageis](https://twitter.com/ageis/) on Twitter, so feel free to keep in touch if you learn any neat tricks like that.

So long as you're working with systemd, it always helps to know about the security/hardening/capabilitly options, many I've helpfully [collated here](https://gist.github.com/ageis/f5595e59b1cddb1513d1b425a323db04).

**Comment by ageis** [comment]
Shit, I just realized it requires deploying DANE and publishing keys in DNS records? Not like I haven't been on board with that idea for years, it's just going to take forever to make it happen. We need sytems/mail/domain administrator tools that can conveniently collect active keys for all members of an organization. See @micahflee's [GPGSync](https://github.com/firstlookmedia/gpgsync), it does something with a similar goal.

**Comment by HLFH** [comment]
Hi @ageis. Big news. OpenPGP.js now supports ed25519. https://github.com/openpgpjs/openpgpjs/pull/618 in `ecc_nist` branch.
